firstRun: false
lu: '36648'
tz: America/Toronto
startTime: 0
endTime: 0
channelNumber: true
subChannelNumber: true
callsign: false
listingId: false
listDateTime: false
duration: false
showId: false
seriesId: false
showName: false
episodeTitle: false
episodeNumber: false
parts: false
partNumber: false
seriesPremiere: false
seasonPremiere: false
seriesFinale: false
seasonFinale: false
repeat: false
newShow: false
rating: false
captioned: false
educational: false
blackwhite: false
subtitled: false
live: false
hd: false
descriptiveVideo: false
inProgress: false
showTypeId: false
breakoutLevel: false
showType: false
year: false
guest: false
cast: false
director: false
starRating: false
description: false
league: false
team1: false
team2: false
sportEvent: false
location: false
showPicture: false
showTitle: true
